### ISSUE TITLE
A question about the Town Star Browser Games in README.md

### ISSUE THREAD

**Issue by F-one-1** [playcanvas/awesome-playcanvas#27]
Town star is a great gamefi.The UI display is excellent and smooth, I wonder if it is completely driven by playcanvas engine or some other method.

**Comment by yaustar** [comment]
The UI is mostly HTML from what I can see in the inspector

**Comment by F-one-1** [comment]
sorry,I mean that its canvas engine use playcanvas entirely ?

**Comment by yaustar** [comment]
It uses playcanvas for the main game rendering and standard html dom elements for the ui

**Comment by F-one-1** [comment]
thanks,I get it.
