### ISSUE TITLE
Is it worth adding a web template ?

### ISSUE THREAD

**Issue by epreston** [playcanvas/awesome-playcanvas#33]
This project promotes the PlayCanvas engine and it's modern API.

https://github.com/epreston/template-web-playcanvas

Is this something that would be listed in this repo ?  Asking for a friend.

I think it's intended as an example for people looking to migrate their game. People who want an ecosystem of tooling, a stable API, commercial support, and a professional editor for their creatives.

**Comment by Maksims** [comment]
I believe such template probably should have an example of loading script types and json scene.

**Comment by willeastcott** [comment]
This is great @epreston! As @Maksims says, though, a template like this should probably at least load one basic script. Happy to add your repos to the awesome list though!

**Comment by epreston** [comment]
You guys think scripts are where they need to be for use outside of editor defined content ?

**Comment by Maksims** [comment]
> You guys think scripts are where they need to be for use outside of editor defined content ?

We've used them in many engine-only projects, and they work well. Currently it is a recommended way of organizing application logic that relates to entities.

**Comment by epreston** [comment]
I would be nice if you could donate a few lines in a PR, thank you in advance.
There's a few open issues and PRs along these lines that have stagnated too.

**Comment by epreston** [comment]
@Maksims How do you resolve the issues with using modern javascript described by @willeastcott here https://github.com/playcanvas/engine/issues/4767 ?
